In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

In [4]:
Data = pd.read_csv('netflix titles.csv', error_bad_lines=False)

/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3444: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
Data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
14953,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
14954,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
14955,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
14956,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
14957,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [6]:
a = Data[['type', 'title', 'country', 'release_year', 'rating', 'listed_in']]
a

,type,title,country,release_year,rating,listed_in
0,Movie,Dick Johnson Is Dead,United States,2020,PG-13,Documentaries
1,TV Show,Blood & Water,South Africa,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries"
2,TV Show,Ganglands,NaN,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act..."
3,TV Show,Jailbirds New Orleans,NaN,2021,TV-MA,"Docuseries, Reality TV"
4,TV Show,Kota Factory,India,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ..."
...,...,...,...,...,...,...
14953,Movie,Zodiac,United States,2007,R,"Cult Movies, Dramas, Thrillers"
14954,TV Show,Zombie Dumb,NaN,2018,TV-Y7,"Kids' TV, Korean TV Shows, TV Comedies"
14955,Movie,Zombieland,United States,2009,R,"Comedies, Horror Movies"
14956,Movie,Zoom,United States,2006,PG,"Children & Family Movies, Comedies"
14957,Movie,Zubaan,India,2015,TV-14,"Dramas, International Movies, Music & Musicals"

In [7]:
b = a.groupby('type')
b['type'].size()

type
Learning Songs by Little Baby Bum: Nursery Rhyme Friends        1
Movie                                                       10521
TV Shane Krakowski                                              1
TV Show                                                      4435
Name: type, dtype: int64

In [52]:
c = a[a.type == 'Movie']
c.reset_index(drop=True)

,type,title,country,release_year,rating,listed_in
0,Movie,Dick Johnson Is Dead,United States,2020,PG-13,Documentaries
1,Movie,My Little Pony: A New Generation,NaN,2021,PG,Children & Family Movies
2,Movie,Sankofa,"United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA,"Dramas, Independent Movies, International Movies"
3,Movie,The Starling,United States,2021,PG-13,"Comedies, Dramas"
4,Movie,Je Suis Karl,"Germany, Czech Republic",2021,TV-MA,"Dramas, International Movies"
...,...,...,...,...,...,...
10516,Movie,Zinzana,"United Arab Emirates, Jordan",2015,TV-MA,"Dramas, International Movies, Thrillers"
10517,Movie,Zodiac,United States,2007,R,"Cult Movies, Dramas, Thrillers"
10518,Movie,Zombieland,United States,2009,R,"Comedies, Horror Movies"
10519,Movie,Zoom,United States,2006,PG,"Children & Family Movies, Comedies"
10520,Movie,Zubaan,India,2015,TV-14,"Dramas, International Movies, Music & Musicals"

In [53]:
d = c.groupby('country')
d['country'].size()

country
, France, Algeria                                       1
Argentina                                              65
Argentina, Brazil, France, Poland, Germany, Denmark     2
Argentina, Chile                                        3
Argentina, Chile, Peru                                  2
                                                       ..
Venezuela                                               2
Venezuela, Colombia                                     2
Vietnam                                                11
West Germany                                            2
Zimbabwe                                                1
Name: country, Length: 651, dtype: int64

In [54]:
e = c[c.country == 'United States']
e.reset_index(drop=True)

,type,title,country,release_year,rating,listed_in
0,Movie,Dick Johnson Is Dead,United States,2020,PG-13,Documentaries
1,Movie,The Starling,United States,2021,PG-13,"Comedies, Dramas"
2,Movie,Grown Ups,United States,2010,PG-13,Comedies
3,Movie,Dark Skies,United States,2013,PG-13,"Horror Movies, Sci-Fi & Fantasy"
4,Movie,Jaws,United States,1975,PG,"Action & Adventure, Classic Movies, Dramas"
...,...,...,...,...,...,...
3636,Movie,Young Adult,United States,2011,R,"Comedies, Dramas, Independent Movies"
3637,Movie,"Yours, Mine and Ours",United States,2005,PG,"Children & Family Movies, Comedies"
3638,Movie,Zodiac,United States,2007,R,"Cult Movies, Dramas, Thrillers"
3639,Movie,Zombieland,United States,2009,R,"Comedies, Horror Movies"
3640,Movie,Zoom,United States,2006,PG,"Children & Family Movies, Comedies"

In [55]:
f = e.groupby('release_year')
f['release_year'].size()

release_year
1942      4
1943      6
1944      4
1945      6
1946      2
       ...
2017    546
2018    473
2019    404
2020    211
2021     49
Name: release_year, Length: 68, dtype: int64

In [88]:
g = e[e.release_year == '2020']
g.reset_index(drop=True)

,type,title,country,release_year,rating,listed_in
0,Movie,Dick Johnson Is Dead,United States,2020,PG-13,Documentaries
1,Movie,Really Love,United States,2020,TV-MA,"Dramas, Independent Movies, Romantic Movies"
2,Movie,The Old Ways,United States,2020,TV-MA,Horror Movies
3,Movie,Milkwater,United States,2020,TV-MA,"Comedies, Dramas, Independent Movies"
4,Movie,Born to Play,United States,2020,TV-MA,"Documentaries, Sports Movies"
...,...,...,...,...,...,...
206,Movie,Bulletproof 2,United States,2020,TV-MA,"Action & Adventure, Comedies"
207,Movie,Norm of the North: Family Vacation,United States,2020,TV-Y7,Children & Family Movies
208,Movie,Straight Up,United States,2020,TV-MA,"Comedies, Independent Movies, LGBTQ Movies"
209,Movie,Norm of the North: Family Vacation,United States,2020,TV-Y7,Children & Family Movies
210,Movie,Straight Up,United States,2020,TV-MA,"Comedies, Independent Movies, LGBTQ Movies"

In [89]:
h = g.groupby('rating')
h['release_year'].size()

rating
G         1
PG       10
PG-13    17
R        44
TV-14    17
TV-G      9
TV-MA    78
TV-PG    16
TV-Y     12
TV-Y7     7
Name: release_year, dtype: int64

In [90]:
i = g[g.rating == 'TV-MA']
i.reset_index(drop=True)

,type,title,country,release_year,rating,listed_in
0,Movie,Really Love,United States,2020,TV-MA,"Dramas, Independent Movies, Romantic Movies"
1,Movie,The Old Ways,United States,2020,TV-MA,Horror Movies
2,Movie,Milkwater,United States,2020,TV-MA,"Comedies, Dramas, Independent Movies"
3,Movie,Born to Play,United States,2020,TV-MA,"Documentaries, Sports Movies"
4,Movie,Picture a Scientist,United States,2020,TV-MA,Documentaries
...,...,...,...,...,...,...
73,Movie,A Fall from Grace,United States,2020,TV-MA,"Dramas, Thrillers"
74,Movie,Leslie Jones: Time Machine,United States,2020,TV-MA,Stand-Up Comedy
75,Movie,Bulletproof 2,United States,2020,TV-MA,"Action & Adventure, Comedies"
76,Movie,Straight Up,United States,2020,TV-MA,"Comedies, Independent Movies, LGBTQ Movies"
77,Movie,Straight Up,United States,2020,TV-MA,"Comedies, Independent Movies, LGBTQ Movies"

In [91]:
j = i.groupby('listed_in')
j['release_year'].size()

listed_in
Action & Adventure                                   2
Action & Adventure, Comedies                         4
Action & Adventure, Dramas, Independent Movies       1
Action & Adventure, Dramas, International Movies     1
Comedies                                             4
Comedies, Dramas, Independent Movies                 3
Comedies, Horror Movies                              1
Comedies, Independent Movies, LGBTQ Movies           2
Comedies, Romantic Movies                            3
Documentaries                                        6
Documentaries, LGBTQ Movies                          3
Documentaries, Music & Musicals                      5
Documentaries, Sports Movies                         3
Dramas, Independent Movies                           3
Dramas, Independent Movies, Romantic Movies          1
Dramas, LGBTQ Movies, Romantic Movies                1
Dramas, Romantic Movies                              2
Dramas, Thrillers                                    2
Horror Movies                                        1
Horror Movies, Independent Movies                    1
Horror Movies, Thrillers                             1
Stand-Up Comedy                                     28
Name: release_year, dtype: int64

In [97]:
k = i[i.listed_in == 'Documentaries, Music & Musicals']
k.reset_index(drop=True)

,type,title,country,release_year,rating,listed_in
0,Movie,Dark City Beneath the Beat,United States,2020,TV-MA,"Documentaries, Music & Musicals"
1,Movie,"Ariana grande: excuse me, i love you",United States,2020,TV-MA,"Documentaries, Music & Musicals"
2,Movie,Shawn Mendes: In Wonder,United States,2020,TV-MA,"Documentaries, Music & Musicals"
3,Movie,Miss Americana,United States,2020,TV-MA,"Documentaries, Music & Musicals"
4,Movie,Miss Americana,United States,2020,TV-MA,"Documentaries, Music & Musicals"